blank_issues_enabled: false
contact_links:
  - name: GitHub Community Discussions
    url: https://github.com/adithya-s-edstem/batch-git-aliases/discussions
    about: Ask questions and discuss with the community
